name: "Build Tarball"

on:
  push:
    tags:
      - nixos-wsl-*
  workflow_call: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tarball
        run: make wsl

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: nixos-wsl.tar.gz
          path: nixos-wsl.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: nixos-wsl.tar.gz
